// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV4kWGOFp29dJZpNjV4HO9sMsx_bWrDFQ',
    appId: '1:800946260951:web:e6b32ef6bc7759a1cbd992',
    messagingSenderId: '800946260951',
    projectId: 'todo-app-2861d',
    authDomain: 'todo-app-2861d.firebaseapp.com',
    storageBucket: 'todo-app-2861d.appspot.com',
    measurementId: 'G-W0WNT3X4T2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_4IEYpqwlKQtZp05xwIi4EOMuNbO5asE',
    appId: '1:800946260951:android:e54a6fac5900f131cbd992',
    messagingSenderId: '800946260951',
    projectId: 'todo-app-2861d',
    storageBucket: 'todo-app-2861d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx84fRbpijJD0jERgCOtTwMd2KCTaYw9s',
    appId: '1:800946260951:ios:8a1b6e9b2390599ccbd992',
    messagingSenderId: '800946260951',
    projectId: 'todo-app-2861d',
    storageBucket: 'todo-app-2861d.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx84fRbpijJD0jERgCOtTwMd2KCTaYw9s',
    appId: '1:800946260951:ios:d7172a6e3f00c935cbd992',
    messagingSenderId: '800946260951',
    projectId: 'todo-app-2861d',
    storageBucket: 'todo-app-2861d.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
